# Generated by Django 5.0.7 on 2025-08-31 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_pet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('final_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('msg_for_user', models.TextField(blank=True, default='waiting')),
                ('msg_for_petsitter', models.TextField(blank=True, default='waiting')),
                ('rating_review_for_petsitter', models.TextField(blank=True, default='')),
                ('rating_review_for_user', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_customer', to=settings.AUTH_USER_MODEL)),
                ('petsitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_sitter', to=settings.AUTH_USER_MODEL)),
                ('service_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mainApp.sitterservice')),
            ],
        ),
    ]
