# Generated by Django 5.0.7 on 2025-08-31 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mainApp.pet'),
        ),
    ]
