# Generated by Django 5.0.7 on 2025-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_order_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating_for_petsitter',
            field=models.PositiveIntegerField(blank=True, help_text='Rating out of 5', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rating_for_user',
            field=models.PositiveIntegerField(blank=True, help_text='Rating out of 5', null=True),
        ),
    ]
