# Generated by Django 5.0.7 on 2025-08-31 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('role', models.CharField(choices=[('petsitter', 'PetSitter'), ('normalUser', 'NormalUser')], default='normalUser', max_length=20)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('pan', models.CharField(blank=True, default='', max_length=20)),
                ('aadhar', models.CharField(blank=True, default='', max_length=20)),
                ('verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
